package types

import (
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

const (
	DefaultCodespace = ModuleName
)

var (
	ErrArgumentMustBePositive               = sdkerrors.Register(ModuleName, 301, "argument must be a positive value")
	ErrArgumentMustBeInteger                = sdkerrors.Register(ModuleName, 302, "argument must be an integer value")
	ErrArgumentMustBeBetween                = sdkerrors.Register(ModuleName, 303, "argument must be between")
	ErrArgumentCannotBeEmpty                = sdkerrors.Register(ModuleName, 304, "argument cannot be empty")
	ErrArgumentCannotBeNegative             = sdkerrors.Register(ModuleName, 305, "argument cannot be negative")
	ErrArgumentMissingOrNonFloat            = sdkerrors.Register(ModuleName, 306, "argument is missing or is not a float")
	ErrBondDoesNotExist                     = sdkerrors.Register(ModuleName, 307, "bond does not exist")
	ErrBondAlreadyExists                    = sdkerrors.Register(ModuleName, 308, "bond already exists")
	ErrBondTokenCannotBeStakingToken        = sdkerrors.Register(ModuleName, 309, "bond token cannot be staking token")
	ErrInvalidStateForAction                = sdkerrors.Register(ModuleName, 310, "cannot perform that action at the current state")
	ErrReserveDenomsMismatch                = sdkerrors.Register(ModuleName, 311, "denom do not match reserve")
	ErrOrderQuantityLimitExceeded           = sdkerrors.Register(ModuleName, 312, "order quantity limits exceeded")
	ErrValuesViolateSanityRate              = sdkerrors.Register(ModuleName, 313, "values violate sanity rate")
	ErrBondDoesNotAllowSelling              = sdkerrors.Register(ModuleName, 314, "bond does not allow selling at the moment")
	ErrFunctionNotAvailableForFunctionType  = sdkerrors.Register(ModuleName, 315, "function is not available for the function type")
	ErrCannotMakeZeroOutcomePayment         = sdkerrors.Register(ModuleName, 316, "cannot make outcome payment because outcome payment is set to nil")
	ErrNoBondTokensOwned                    = sdkerrors.Register(ModuleName, 317, "no bond tokens of this bond are owned")
	ErrCannotBurnMoreThanSupply             = sdkerrors.Register(ModuleName, 318, "cannot burn more tokens than the current supply")
	ErrFeesCannotBeOrExceed100Percent       = sdkerrors.Register(ModuleName, 319, "sum of fees is or exceeds 100 percent")
	ErrFromAndToCannotBeTheSameToken        = sdkerrors.Register(ModuleName, 320, "from and to tokens cannot be the same token")
	ErrCannotMintMoreThanMaxSupply          = sdkerrors.Register(ModuleName, 321, "cannot mint more tokens than the max supply")
	ErrMaxPriceExceeded                     = sdkerrors.Register(ModuleName, 322, "max price exceeded")
	ErrInsufficientReserveToBuy             = sdkerrors.Register(ModuleName, 323, "insufficient reserve was supplied to perform buy order")
	ErrIncorrectNumberOfFunctionParameters  = sdkerrors.Register(ModuleName, 324, "incorrect number of function parameters")
	ErrFunctionParameterMissingOrNonFloat   = sdkerrors.Register(ModuleName, 325, "parameter is missing or is not a float")
	ErrFunctionRequiresNonZeroCurrentSupply = sdkerrors.Register(ModuleName, 326, "function requires the current supply to be non zero")
	ErrTokenIsNotAValidReserveToken         = sdkerrors.Register(ModuleName, 327, "token is not a valid reserve token")
	ErrSwapAmountTooSmallToGiveAnyReturn    = sdkerrors.Register(ModuleName, 328, "swap amount too small to give any return")
	ErrSwapAmountCausesReserveDepletion     = sdkerrors.Register(ModuleName, 329, "swap amount too large and causes reserve to be depleted")
	ErrInvalidCoinDenomination              = sdkerrors.Register(ModuleName, 330, "invalid coin denomination")
	ErrMaxSupplyDenomDoesNotMatchTokenDenom = sdkerrors.Register(ModuleName, 331, "max supply denom does not match token denom")
	ErrDidNotEditAnything                   = sdkerrors.Register(ModuleName, 332, "did not edit anything from the bond")
	ErrBondTokenCannotAlsoBeReserveToken    = sdkerrors.Register(ModuleName, 333, "token cannot also be a reserve token")
	ErrDuplicateReserveToken                = sdkerrors.Register(ModuleName, 334, "cannot have duplicate tokens in reserve tokens")
	ErrUnrecognizedFunctionType             = sdkerrors.Register(ModuleName, 335, "unrecognized function type")
	ErrIncorrectNumberOfReserveTokens       = sdkerrors.Register(ModuleName, 336, "incorrect number of reserve tokens")
	ErrInvalidFunctionParameter             = sdkerrors.Register(ModuleName, 337, "invalid function parameter")
	ErrArgumentMissingOrNonUInteger         = sdkerrors.Register(ModuleName, 338, "argument is missing or is not an unsigned integer")
	ErrArgumentMissingOrNonBoolean          = sdkerrors.Register(ModuleName, 339, "argument is missing or is not true or false")
)
